server:
  port: 9191

spring:
  application:
    name: ai-java-demo

  ai:
    openai:
      api-key: ${SKO_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-3-small
    mcp:
      server:
        id: ai-java-demo
        name: ai-java-demo
        transport: sse
        version: "1.0.0"
        type: SYNC
        instructions: "Demo MCP Server with tools for Smart Search"
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true


  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Shaik
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework.ai.mcp: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.web.reactive.handler: TRACE


management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
